services:
  backend:
    build:
      context: .
    container_name: backend
    ports:
      - "8080:5001"
    depends_on:
      - db
      - cache

  db:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=db_ms
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  cache:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
